# Generated by Django 2.1.3 on 2018-12-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
