# Generated by Django 2.1.3 on 2018-12-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0003_auto_20181203_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='till.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='saletracker',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='till.Sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products_from_trans',
            field=models.ManyToManyField(related_name='le_sales', to='till.SaleTracker'),
        ),
    ]
