# Generated by Django 2.1.3 on 2018-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0005_auto_20181203_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount_sold',
        ),
        migrations.AddField(
            model_name='saletracker',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
    ]
